server:
  port: 9002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    initialization-mode: never
#    initialization-mode: always
    password: root
    url: jdbc:postgresql://localhost:5432/departmentservicedb
    username: postgres
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true